<a href="https://colab.research.google.com/github/vamshi10296/DATA-ANALYTIC_PY/blob/main/pandas3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

dct = {
    'name': ['tom', 'Nick', 'krish', 'jack' ],
    'age':[20,21,19,18],
    'roll':[1,2,3,4]

}
df = pd.DataFrame(dct )
df1 = pd.DataFrame(dct)

display(df)
display(df1)

    name  age  roll
0    tom   20     1
1   Nick   21     2
2  krish   19     3
3   jack   18     4

    name  age  roll
0    tom   20     1
1   Nick   21     2
2  krish   19     3
3   jack   18     4

In [ ]:
import pandas as pd
df = pd.read_csv("student_data.csv")

# functions

# 1head
# df.head(3)

# 2tail
df.tail(3)

#3shape
# df.shape

#4info
# df.info()

#5describe
# df.describe()


#columns
# df.columns


#index
# df.index


# df[['study_hours','internet_usage']]


df['study_hours','internet_usage']

IndentationError: unexpected indent (2471076933.py, line 33)

In [64]:
import pandas as pd
df=pd.read_csv('student_data.csv')
# from 1st
# df.head()
# from last
# df.tail()
# give no. of rows and columns
# df.shape
# df.info()
# df.describe()
# df.columns
# df.index
# single column
# df['internet_usage']
# multi column
# df[['study_hours','internet_usage']]
# df.iloc[0: 5]
# it gives codition given in any column with any constant we want
# df.loc[df['study_hours']==11]
# df.loc[df['assignments_completed']== 8].iloc[1]
# df[df['assignments_completed']>3]

# to add new column
# df['age']=20

# to rename any columns
# df.rename(columns={'assignments_completed':'assignments'}, inplace=True)
# df

#Remove rows

df.drop(1)

# Remove column
df.drop('internet_usage', axis=1)


#Remove missing values
df.dropna()


 # Sort values by a column
df.sort_values(by='study_hours')

#sort index
df.sort_index(ascending=False)

#check for missing values
df.isnull()


#check for non-missing values
df.notnull()


#replace missing values
df.fillna(0)


#find unique values
df.unique()       #for a series only

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
9999,2,70,6,11,16,52,78.96,Placed
9998,10,75,7,5,8,52,88.61,Placed
9997,10,44,8,5,10,37,95.94,Placed
9996,7,98,6,9,4,87,100.00,Placed
9995,2,58,9,7,8,88,69.31,Not Placed
...,...,...,...,...,...,...,...,...
4,5,52,8,6,8,40,78.82,Placed
3,8,99,9,8,4,55,90.17,Placed
2,11,60,7,6,10,45,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
0,7,56,8,7,10,62,100.00,Placed

In [68]:
import pandas as pd

data = {
    'Name': ['Aman', 'Riya', 'Karan'],
    'Marks': [85, None, 78],
    'Age': [20, 21, None]
}

df = pd.DataFrame(data)


print(df)

# Remove rows with missing values
df.dropna()

    Name  Marks   Age
0   Aman   85.0  20.0
1   Riya    NaN  21.0
2  Karan   78.0   NaN

   Name  Marks   Age
0  Aman   85.0  20.0